In [1]:
import requests
import csv

response = requests.get("https://gorest.co.in/public-api/users?_format=json&access-token=H4lYmIGLXZkDlpy_w0ZVS5rgcpDXbN7fhRRy")
employees = response.json()

In [2]:
employees

{'code': 200,
 'meta': {'pagination': {'total': 2361, 'pages': 119, 'page': 1, 'limit': 20}},
 'data': [{'id': 3921,
   'name': 'Adrienne',
   'email': 'Dixie_Tromp86@hotmail.com',
   'gender': 'male',
   'status': 'active'},
  {'id': 43,
   'name': 'Allasani Peddana',
   'email': 'allasani.peddan@15ce.com',
   'gender': 'female',
   'status': 'active'},
  {'id': 2275,
   'name': 'API Monitoring:51a9wj',
   'email': 'apimonitoring51a9wj@synthetic.com',
   'gender': 'male',
   'status': 'active'},
  {'id': 3014,
   'name': 'Sushree',
   'email': 'shre4166e@email.com',
   'gender': 'female',
   'status': 'active'},
  {'id': 23,
   'name': 'Ms. Dhanu Malikhh',
   'email': 'ms_dhanu_malik@reinger.co',
   'gender': 'male',
   'status': 'active'},
  {'id': 3341,
   'name': 'John Shoe',
   'email': 'sawjohn@walsoft.com',
   'gender': 'female',
   'status': 'inactive'},
  {'id': 2277,
   'name': 'Tioss',
   'email': 'tio@email.comas',
   'gender': 'male',
   'status': 'active'},
  {'id': 3923,
   'name': 'Mili Mittar',
   'email': 'test487@hotmail.com',
   'gender': 'female',
   'status': 'active'},
  {'id': 3013,
   'name': 'Tiago Barbosa Vencio',
   'email': 'tiago@gmail.com',
   'gender': 'male',
   'status': 'active'},
  {'id': 66,
   'name': 'Allasani Peddana',
   'email': 'allasani.peddana@15ce.com',
   'gender': 'male',
   'status': 'active'},
  {'id': 40,
   'name': 'Gretchen Hauck MD',
   'email': 'Brooklyn53@hotmail.com',
   'gender': 'male',
   'status': 'active'},
  {'id': 1620,
   'name': 'Mounika39',
   'email': 'f@gmail.com',
   'gender': 'male',
   'status': 'inactive'},
  {'id': 2286,
   'name': 'API Monitoring:ofkcv',
   'email': 'apimonitoringofkcv@synthetic.com',
   'gender': 'male',
   'status': 'active'},
  {'id': 2287,
   'name': 'Maikon Pinto',
   'email': 'maikon@hotmail.com',
   'gender': 'male',
   'status': 'active'},
  {'id': 3965,
   'name': 'Ken Tester',
   'email': 'Test@gmail.com',
   'gender': 'male',
   'status': 'active'},
  {'id': 2299,
   'name': 'name1634559042',
   'email': 'test1634559042@academy.com',
   'gender': 'male',
   'status': 'active'},
  {'id': 2301,
   'name': 'name1634559084',
   'email': 'test1634559084@academy.com',
   'gender': 'male',
   'status': 'active'},
  {'id': 2303,
   'name': 'name1634559117',
   'email': 'test1634559117@academy.com',
   'gender': 'male',
   'status': 'active'},
  {'id': 36,
   'name': 'Mina Kaniyar CPA',
   'email': 'cpa_mina_kaniyar@willms.co',
   'gender': 'female',
   'status': 'inactive'},
  {'id': 37,
   'name': 'Dharitri Talwar',
   'email': 'talwar_dharitri@jakubowski.net',
   'gender': 'male',
   'status': 'active'}]}

In [3]:
employees['data']

[{'id': 3921,
  'name': 'Adrienne',
  'email': 'Dixie_Tromp86@hotmail.com',
  'gender': 'male',
  'status': 'active'},
 {'id': 43,
  'name': 'Allasani Peddana',
  'email': 'allasani.peddan@15ce.com',
  'gender': 'female',
  'status': 'active'},
 {'id': 2275,
  'name': 'API Monitoring:51a9wj',
  'email': 'apimonitoring51a9wj@synthetic.com',
  'gender': 'male',
  'status': 'active'},
 {'id': 3014,
  'name': 'Sushree',
  'email': 'shre4166e@email.com',
  'gender': 'female',
  'status': 'active'},
 {'id': 23,
  'name': 'Ms. Dhanu Malikhh',
  'email': 'ms_dhanu_malik@reinger.co',
  'gender': 'male',
  'status': 'active'},
 {'id': 3341,
  'name': 'John Shoe',
  'email': 'sawjohn@walsoft.com',
  'gender': 'female',
  'status': 'inactive'},
 {'id': 2277,
  'name': 'Tioss',
  'email': 'tio@email.comas',
  'gender': 'male',
  'status': 'active'},
 {'id': 3923,
  'name': 'Mili Mittar',
  'email': 'test487@hotmail.com',
  'gender': 'female',
  'status': 'active'},
 {'id': 3013,
  'name': 'Tiago Barbosa Vencio',
  'email': 'tiago@gmail.com',
  'gender': 'male',
  'status': 'active'},
 {'id': 66,
  'name': 'Allasani Peddana',
  'email': 'allasani.peddana@15ce.com',
  'gender': 'male',
  'status': 'active'},
 {'id': 40,
  'name': 'Gretchen Hauck MD',
  'email': 'Brooklyn53@hotmail.com',
  'gender': 'male',
  'status': 'active'},
 {'id': 1620,
  'name': 'Mounika39',
  'email': 'f@gmail.com',
  'gender': 'male',
  'status': 'inactive'},
 {'id': 2286,
  'name': 'API Monitoring:ofkcv',
  'email': 'apimonitoringofkcv@synthetic.com',
  'gender': 'male',
  'status': 'active'},
 {'id': 2287,
  'name': 'Maikon Pinto',
  'email': 'maikon@hotmail.com',
  'gender': 'male',
  'status': 'active'},
 {'id': 3965,
  'name': 'Ken Tester',
  'email': 'Test@gmail.com',
  'gender': 'male',
  'status': 'active'},
 {'id': 2299,
  'name': 'name1634559042',
  'email': 'test1634559042@academy.com',
  'gender': 'male',
  'status': 'active'},
 {'id': 2301,
  'name': 'name1634559084',
  'email': 'test1634559084@academy.com',
  'gender': 'male',
  'status': 'active'},
 {'id': 2303,
  'name': 'name1634559117',
  'email': 'test1634559117@academy.com',
  'gender': 'male',
  'status': 'active'},
 {'id': 36,
  'name': 'Mina Kaniyar CPA',
  'email': 'cpa_mina_kaniyar@willms.co',
  'gender': 'female',
  'status': 'inactive'},
 {'id': 37,
  'name': 'Dharitri Talwar',
  'email': 'talwar_dharitri@jakubowski.net',
  'gender': 'male',
  'status': 'active'}]

In [4]:
import csv 

with open('employees.csv', 'w', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=['name', 'gender', 'email', 'is_active'])
    writer.writeheader()
    for employee in employees['data']:
        name = employee['name']
        email = employee['email']
        gender = employee['gender']
        is_active = 1 if employee['status'] == 'active' else 0
        writer.writerow({'name': name, 'gender': gender, 'email': email, 'is_active': is_active})

In [5]:
import pandas as pd

data = pd.read_csv('employees.csv')
data

,name,gender,email,is_active
0,Adrienne,male,Dixie_Tromp86@hotmail.com,1
1,Allasani Peddana,female,allasani.peddan@15ce.com,1
2,API Monitoring:51a9wj,male,apimonitoring51a9wj@synthetic.com,1
3,Sushree,female,shre4166e@email.com,1
4,Ms. Dhanu Malikhh,male,ms_dhanu_malik@reinger.co,1
5,John Shoe,female,sawjohn@walsoft.com,0
6,Tioss,male,tio@email.comas,1
7,Mili Mittar,female,test487@hotmail.com,1
8,Tiago Barbosa Vencio,male,tiago@gmail.com,1
9,Allasani Peddana,male,allasani.peddana@15ce.com,1
10,Gretchen Hauck MD,male,Brooklyn53@hotmail.com,1
11,Mounika39,male,f@gmail.com,0
12,API Monitoring:ofkcv,male,apimonitoringofkcv@synthetic.com,1
13,Maikon Pinto,male,maikon@hotmail.com,1
14,Ken Tester,male,Test@gmail.com,1
15,name1634559042,male,test1634559042@academy.com,1
16,name1634559084,male,test1634559084@academy.com,1
17,name1634559117,male,test1634559117@academy.com,1
18,Mina Kaniyar CPA,female,cpa_mina_kaniyar@willms.co,0
19,Dharitri Talwar,male,talwar_dharitri@jakubowski.net,1